apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: doctor-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: FLASK_APP
              valueFrom:
                configMapKeyRef:
                  name: doctor-config
                  key: FLASK_APP
            - name: FLASK_ENV
              valueFrom:
                configMapKeyRef:
                  name: doctor-config
                  key: FLASK_ENV
            - name: SQLALCHEMY_DATABASE_URI
              value: postgresql://root:root@postgres/doctor_db

