apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: patient-service:latest  # Ensure it's the correct image name
          imagePullPolicy: Never  # Prevent Kubernetes from pulling the image
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30001  #  Explicitly setting a NodePort
  type: NodePort  #  Allows external access via Minikube

