name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: group3
          POSTGRES_PASSWORD: group3pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 🔽 Microservices Loop
      - name: Run tests and build for all services
        run: |
          SERVICES=("patient-service" "doctor-service" "appointment-service" "notification-service")

          for SERVICE in "${SERVICES[@]}"; do
            echo "🔧 Processing $SERVICE"

            pip install -r $SERVICE/requirements.txt
            pip install pytest requests-mock

            echo "▶️ Running tests for $SERVICE"
            pytest $SERVICE/tests --maxfail=3 --disable-warnings -v

            echo "🐳 Building Docker image for $SERVICE"
            docker build -t $SERVICE:latest ./$SERVICE

            echo "✅ Finished $SERVICE"
            echo "-------------------------------------"
          done
